ones:
        name: Ones
        class: SingleOutputSource
        categories: ["/NumPy/Sources"]
        blockType: [all]

zeros:
        name: Zeros
        copy: ones

linspace:
        name: LinSpace
        class: SingleOutputSource
        subclass: True
        categories: ["/NumPy/Sources"]
        blockType: [int, uint, float]
        kwargs: [useDType=True, callPostBuffer=True, useShape=False]
        funcArgs:
                - {name: start, dtype: blockType, testValue1: 10, testValue2: 2}
                - {name: stop, dtype: blockType, testValue1: 2, testValue2: 10}
                - {name: numValues, dtype: uint, testValue1: 3, testValue2: 5, ">": 0, badValues: [0]}

logspace:
        name: LogSpace
        copy: linspace

geomspace:
        name: GeomSpace
        copy: linspace
